# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Cache Test debug

on:
  workflow_dispatch:
      
jobs:
   # test-issuev4:
   #   runs-on: ubuntu-latest

   #   steps:
   #     - name: Checkout repo
   #       uses: actions/checkout@v5
   #     # - uses: HarithaVattikuti/setup-node@TestArchKey
   #     - uses: actions/setup-node@v6
   #       with:
   #         node-version: ${{ env.NODE_VERSION }}
   #         cache: 'npm'
   #         cache-dependancy-path: ${{ env.repo_dir }}/package-lock.json

   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Restore Node.js modules cache (restore-only)
      - name: Restore Node modules cache
        uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-npm-
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      # Install dependencies
      - run: npm install
