# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Cache Test debug

on:
  workflow_dispatch:
      
jobs:
   test-issue:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
       # - uses: HarithaVattikuti/setup-node@TestArchKey
       - uses: actions/setup-node@v3
         with:
           node-version: ${{ env.NODE_VERSION }}
           cache: 'npm'
           cache-dependancy-path: ${{ env.repo_dir }}/package-lock.json
       - run: |
           npm ci
           npm run build --if-present
  
