name: node canary test

on:
  workflow_dispatch:

jobs:
  testoncanary:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13]
        node-version:
          - 20-v8-canary
          - 24-v8-canary
          - 24.0.0-v8-canary
          - 20.0.0-v8-canary
          - 20.0.0-v8-canary20221101e50e45c9f8
          - 24.0.0-v8-canary2025030537242e55ac
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: ./
        with:
          node-version: ${{ matrix.node-version }}
      - name: Verify node and npm
        run: |
          canaryVersion="${{ matrix.node-version }}"
          majorVersion=$(echo $canaryVersion | cut -d- -f1)
          __tests__/verify-node.sh "$majorVersion"
        shell: bash
