name: Go lang default install


on:
  push:
  workflow_dispatch:


jobs:
  build:
    name: Build on macOS 13
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: |
           npm ci
           npm run build --if-present
