name: Java Corretto cache

on: 
  workflow_dispatch:
jobs:
  Corretto-8:
    runs-on: ${{matrix.os}}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest,macos-latest,macos-13]
    steps:
      - name: Setup Java 
        uses: HarithaVattikuti/setup-java@testcorretto
        with:
          distribution: 'corretto'
          java-version: '8'
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/

      - name: Check toolcache folder
        run: |
          echo "Files in /opt/hostedtoolcache/Java_Corretto_jdk/8.432.06-1/x64:"
          ls -la /opt/hostedtoolcache/Java_Corretto_jdk/8.432.06-1/x64

      - name: Setup Java Again
        uses: HarithaVattikuti/setup-java@testcorretto
        with:
          distribution: 'corretto'
          java-version: '8'

  Corretto-17:
    runs-on: ${{matrix.os}}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest,macos-latest, macos-13]
    steps:
      - name: Setup Java 
        uses: HarithaVattikuti/setup-java@testcorretto
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/

      - name: Check toolcache folder
        run: |
          echo "Files in /opt/hostedtoolcache/Java_Corretto_jdk/17.0.13-11.1/x64:"
          ls -la /opt/hostedtoolcache/Java_Corretto_jdk/17.0.13-11.1/x64

      - name: Setup Java Again
        uses: HarithaVattikuti/setup-java@testcorretto
        with:
          distribution: 'corretto'
          java-version: '17'

