name: Validate Java e2e Sap

on:
  workflow_dispatch:
  
jobs:

  setup-java-ea-versions-sapmachine:
    name: sapmachine ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }}
    needs: setup-java-major-minor-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: ['17-ea', '21-ea']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: Shegox/setup-java@main
        with:
          java-version: ${{ matrix.version }}
          distribution: sapmachine
      - name: Verify Java
        run: bash __tests__/verify-java.sh "${{ matrix.version }}" "${{ steps.setup-java.outputs.path }}"
        shell: bash
        
  setup-java-major-versions:
    name: ${{ matrix.distribution }} ${{ matrix.version }} (jdk-x64) - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        distribution: [
            'sapmachine'
          ] # internally 'adopt-hotspot' is the same as 'adopt'
        version: ['21', '11', '17']
        include:
             # Add Semeru configuration here
          - distribution: 'sapmachine'
            os: macos-13
            version: '21'
          - distribution: 'sapmachine'
            os: macos-13
            version: '11'
          - distribution: 'sapmachine'
            os: macos-13
            version: '17'
         
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: Shegox/setup-java@main
        with:
          java-version: ${{ matrix.version }}
          distribution: ${{ matrix.distribution }}
