name: Java Corretto cache

on: 
  workflow_dispatch:
jobs:
  Corretto-8:
    runs-on: ${{matrix.os}}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest,macos-latest,windows-latest,macos-13]
    steps:
      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/

      - name: Setup Java Again
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '8'

  Corretto-17:
    runs-on: ${{matrix.os}}
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest,macos-latest,windows-latest, macos-13]
    steps:
      - name: Setup Java 
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      
      - name: Check Runner ToolCache
        run: |
          ls -la $RUNNER_TOOL_CACHE/Java_Corretto_jdk/

      - name: Setup Java Again
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
