name: Generate Node.js packages
run-name: Generate Node.js ${{ inputs.VERSION || '16.20.0' }}
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Node.js version to build and upload'
        required: true
        default: '16.20.0'
      PUBLISH_RELEASES:
        description: 'Whether to publish releases'
        required: true
        type: boolean
        default: false
  #pull_request:
   # paths-ignore:
    #- 'versions-manifest.json'
    #- 'LICENSE'
    #- '**.md'
    #branches:
    #- 'main'

jobs:
  node:
    name: Node
    uses: HarithaVattikuti/node-versions/.github/workflows/build-node-packages.yml@testnewversions
    with:
      VERSION: ${{ inputs.VERSION || '16.20.0' }}
      PUBLISH_RELEASES: ${{ inputs.PUBLISH_RELEASES || false }}

      #tool-version: ${{ inputs.VERSION || '16.20.0' }}
      #publish-release: ${{ inputs.PUBLISH_RELEASES || false }}
    secrets: inherit
