name:  node performance test

on:
  workflow_dispatch:

jobs:
  test-npm-ci-hang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, macos-14, macos-13, ubuntu-24.04, windows-latest, ubuntu-22.04-arm, ubuntu-24.04-arm, windows-11-arm]
        vers: [20, 22, 24 ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.vers }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.vers }}

      - name: Show node and npm versions
        run: |
          node --version
          npm --version

      - name: Run npm ci (watch for hang)
        run: npm ci
