name:  npm ci hang check

on:
  workflow_dispatch:

jobs:
  test-npm-ci-hang:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-22.04]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Show node and npm versions
        run: |
          node --version
          npm --version

      - name: Run npm ci (watch for hang)
        run: npm ci
