name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-nodeversion:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        version: ['20','latest','current','23','node','18.0.0-rc.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: ${{ matrix.version }}

  setup-nodeversionmirror:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        version: ['20','latest','current','23','node','18.0.0-rc.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: ${{ matrix.version }}
          mirror-url: 'https://nodejs.org/download/rc'
