name: Test node 22 on Win

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13, macos-latest, ubuntu-latest, ubuntu-24.04]
    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4
        #with:
         # submodules: true

      - uses: actions/setup-node@v4
        with:
            node-version: 18
            check-latest: true

      - run: npm ci
