name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  testreg:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: ['22','current','23','node','18.0.0-rc.2','lts/*','v25.0.0-nightly']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js with mirrorURL
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
          mirror-url: 'https://nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v   


  # testmarcomirror:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #       version: ['22','current','23','node','lts/*','18.0.0-rc.2','v25.0.0-nightly']

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js with mirrorURL
  #       uses: marco-ippolito/setup-node@mirror
  #       with:
  #         node-version: ${{ matrix.version }}
  #         mirror-url: 'https://nodejs.org/'
  #         mirror-token: ${{secrets.GITHUB_TOKEN}}
  #     - name: Verify Node.js installation
  #       run: node -v  
