name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  testreg:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        version: ['22','latest','current','23','node','18.0.0-rc.2','lts/*']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js with mirrorURL
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.version }}
      - name: Verify Node.js installation
        run: node -v   


  testmarcomirror:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
        version: ['22','latest','current','23','node','lts/*']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.version }}
          mirror-url: 'https://nodejs.org/'
      - name: Verify Node.js installation
        run: node -v  
