name: Test Setup Node with MirrorURL

on:
  workflow_dispatch:

jobs:
  setup-nodeversion20:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '20'

  setup-nodeversionlatest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: 'latest'
  
  setup-nodeversioncurrent:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: 'current'

  setup-nodeversionnonLTS:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '23'

  setup-nodeversion20mirror:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '20'
          mirror-url: 'https://nodejs.org/download/v8-canary/'

  setup-nodeversionlatestmirror:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: 'latest'
          mirror-url: 'https://nodejs.org/download/v8-canary/'

  
  setup-nodeversioncurrentmirror:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: 'current'
          mirror-url: 'https://nodejs.org/download/v8-canary/'

  setup-nodeversionnonLTSmirror:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with mirrorURL
        uses: aparnajyothi-y/setup-node@add-mirror-url
        with:
          node-version: '23'
          mirror-url: 'https://nodejs.org/download/v8-canary/'
