name: Node.js Reusable WF test

on:
  workflow_dispatch:
      
jobs:
   test-issue:
     runs-on: ${{matrix.os}}
     strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
       - uses: HarithaVattikuti/setup-node@testrw1
         with:
           node-version: ${{ env.NODE_VERSION }}
           cache: 'npm'
           cache-dependancy-path: ${{ env.repo_dir }}/package-lock.json
       - run: |
           npm ci
           npm run build --if-present
